set ::env(PDK) "sky130A"
set ::env(PDKPATH) "/Business/EDA_wx_company/jli/.volare/sky130A"
set ::env(STD_CELL_LIBRARY) "sky130_fd_sc_hd"
set ::env(SCLPATH) "/Business/EDA_wx_company/jli/.volare/sky130A/sky130_fd_sc_hd"
set ::env(DESIGN_DIR) "/openlane/designs/core"
set ::env(DESIGN_NAME) "core"
set ::env(VERILOG_FILES) "/openlane/designs/core/src/core.v"
set ::env(CLOCK_PORT) "clock"
set ::env(CLOCK_PERIOD) "8.0"
set ::env(FP_PDN_MULTILAYER) "1"
set ::env(SYNTH_STRATEGY) "DELAY 1"
set ::env(FP_CORE_UTIL) "45"
set ::env(PL_TARGET_DENSITY) "0.5"
